services:
  gta-wiki-scraper:
    build: .
    container_name: gta-wiki-scraper
    volumes:
      - ./output:/app/output/
      - ./scraped:/app/scraped/
    command: python main.py
    environment:
      - CACHE_EXPIRATION_IN_HOURS = 168
      - LOG_LEVEL = warn #debug: minimal|info: all logs|warn: only show missing data